# =========================================================
# ZERO HOUR CORE: REACTOR ENGINE - v23.2
# =========================================================
# ROLE: Server Watchdog & Sovereign Log Parser
# STRATEGY: Full Vertical Source - No Semicolons - No Shorthand
# =========================================================
# PHASE 16.5 UPDATE:
# FIX: 100% Bracket-Free payload to defeat parser corruption.
# SURGERY: Danger Zone Split Complete. All economy math removed.
# FIX: The Proven Syntax Fix. -logfile and the path are now 
#      passed as separate array items to simulate a space, 
#      forcing Unity to lock onto a static log name in the _Data folder.
# FIX: Iron Grip wait loop stops Tailer from dying during slow boots.
# =========================================================

import os
import time
import subprocess
import logging
from PySide6.QtCore import QThread, Signal

# Initialize standard Paradoxal Logger
log = logging.getLogger("Paradoxal")

class LogTailer(QThread):
    """ 
    The Eyes of the Manager.
    A hyper-efficient file reader decoupled from all mathematics.
    Reads the absolute log path and broadcasts raw lines to the Hub.
    """
    line_signal = Signal(str)
    
    # Legacy dummy signals left intact temporarily to prevent 
    # PySide6 AttributeErrors before the Hub is fully re-wired.
    telnet_signal = Signal(str) 
    ledger_signal = Signal()    

    def __init__(self, log_path, db_manager=None):
        super().__init__()
        self.original_path = log_path
        self.active_log_path = log_path
        self.is_running = False

    def _resolve_log_path(self):
        """
        Attempts to find the actual log file natively generated by Unity.
        Checks original path, and _Data variant.
        """
        if os.path.exists(self.original_path):
            self.active_log_path = self.original_path
            return True
            
        alt_path = self.original_path.replace("7DaysToDie_Data", "7DaysToDieServer_Data")
        if os.path.exists(alt_path):
            self.active_log_path = alt_path
            return True
            
        # Sometimes Unity dumps it inside our custom UserDataFolder fallback
        base_dir = os.path.dirname(os.path.dirname(self.original_path))
        save_data_path = os.path.join(base_dir, "SaveData", "output_log.txt")
        if os.path.exists(save_data_path):
            self.active_log_path = save_data_path
            return True
            
        return False

    def run(self):
        """ Primary execution loop for the file tailer. """
        self.is_running = True
        self.line_signal.emit(" Waiting for server to allocate RAM and generate log file...")
        
        # 1. Brief pause to allow Unity to boot and wipe any existing log from yesterday
        time.sleep(3)
        
        # 2. Iron Grip Loop: Wait up to 120 seconds for the server to actually create the file
        wait_cycles = 0
        file_found = False
        
        while self.is_running and wait_cycles < 60:
            if self._resolve_log_path() and os.path.exists(self.active_log_path):
                file_found = True
                break
            time.sleep(2)
            wait_cycles = wait_cycles + 1
            
        if not self.is_running:
            return
            
        if not file_found:
            self.line_signal.emit(f" WARN: Server boot timed out or log file missing at: {self.original_path}")
            return
            
        self.line_signal.emit(f" Tailer successfully attached to: {self.active_log_path}")
        log.info(f" Tailer active on: {self.active_log_path}")
        
        try:
            with open(self.active_log_path, 'r', encoding='utf-8', errors='replace') as f:
                f.seek(0, 2) 
                
                while self.is_running:
                    line = f.readline()
                    
                    if line:
                        clean_line = line.strip()
                        self.line_signal.emit(clean_line)
                    else:
                        time.sleep(0.1) 
                        
        except Exception as e:
            log.error(f" Tailer Critical Failure: {str(e)}")
            self.line_signal.emit(f" CRITICAL: Tailer died -> {e}")
            
    def stop(self):
        self.is_running = False


class ServerWatchdog(QThread):
    """ The Guardian of the Server Process. """
    status_signal = Signal(str, str)
    log_signal = Signal(str)

    def __init__(self, server_path):
        super().__init__()
        self.server_path = server_path
        self.is_running = False
        self.auto_restart = True
        
        self.attach_mode = False
        self.attached_pid = None

    def _is_pid_alive(self, pid):
        try:
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            
            output = subprocess.check_output(
                list(("tasklist", "/FI", f"PID eq {pid}")),
                startupinfo=startupinfo,
                text=True
            )
            return str(pid) in output
        except Exception:
            return False

    def run(self):
        exe_path = os.path.join(self.server_path, "7DaysToDieServer.exe")
        if not os.path.exists(exe_path):
            self.log_signal.emit(" ERROR: Executable not found.")
            return

        while self.is_running:
            
            if self.attach_mode and self.attached_pid:
                self.log_signal.emit(f" Sovereignty Lock: Monitoring existing PID {self.attached_pid}")
                
                while self.is_running and self._is_pid_alive(self.attached_pid):
                    time.sleep(2)
                    
                if self.is_running:
                    self.log_signal.emit(" Attached Server Process Terminated!")
                    self.status_signal.emit("STATUS: CRASHED", "#e74c3c")
                    self.attach_mode = False
                    self.attached_pid = None
                    time.sleep(10)
                    continue 
                else:
                    self.status_signal.emit("STATUS: OFFLINE", "#95a5a6")
                    break

            self.log_signal.emit(" Initializing Sovereign Boot Sequence...")
            self.status_signal.emit("STATUS: STARTING", "#2ecc71")
            
            try:
                user_data_folder = os.path.join(self.server_path, "SaveData")
                
                # The exact native location, forcing a static name to prevent timestamps
                log_file_path = os.path.join(self.server_path, "7DaysToDieServer_Data", "output_log.txt")

                # We MUST physically create the SaveData and _Data directories before 
                # the engine boots to prevent Unity initialization crashes.
                log_dir = os.path.dirname(log_file_path)
                if not os.path.exists(log_dir):
                    os.makedirs(log_dir, exist_ok=True)
                    
                if not os.path.exists(user_data_folder):
                    os.makedirs(user_data_folder, exist_ok=True)

                # Bulletproof Boot Command Array
                # THE FIX: -logfile and log_file_path are separate elements, simulating a space.
                cmd = list((
                    exe_path, 
                    "-configfile=serverconfig.xml", 
                    "-nographics", 
                    "-batchmode", 
                    "-dedicated",
                    f"-UserDataFolder={user_data_folder}",
                    "-logfile",
                    log_file_path
                ))
                
                process = subprocess.Popen(
                    cmd, 
                    cwd=self.server_path,
                    creationflags=subprocess.CREATE_NO_WINDOW
                )
                
                pid = process.pid
                self.log_signal.emit(f" Process Hooked. PID: {pid}")
                self.status_signal.emit(f"STATUS: ONLINE (PID {pid})", "#2ecc71")

                while process.poll() is None:
                    if not self.is_running:
                        process.terminate()
                        try:
                            process.wait(timeout=5)
                        except subprocess.TimeoutExpired:
                            process.kill()
                        break
                    time.sleep(2)

                if self.is_running:
                    if self.auto_restart:
                        self.log_signal.emit(" Reactor Failure Detected!")
                        self.status_signal.emit("STATUS: CRASHED", "#e74c3c")
                        time.sleep(10)
                    else:
                        self.status_signal.emit("STATUS: OFFLINE", "#95a5a6")
                        break
                else:
                    self.status_signal.emit("STATUS: OFFLINE", "#95a5a6")
                    break

            except Exception as e:
                log.error(f" Watchdog Execution Failed: {str(e)}")
                break

    def stop(self):
        self.is_running = False